<style>
    #oink-checkout {
        border-radius: 4px;
        background:white;
    }


    #oink-cart-button {
        display: inline-block;
        margin-top: <?php echo Mage::getStoreConfig("oink/checkoutbutton/oink_cart_checkout_margin_top").'px;'; ?>
    }

    .oink-h2
    {
        padding-bottom: 5px;
        font-size: 19px;
        display: block;
        text-align: center;
        font-family: Helvetica,'Open Sans Condensed',sans-serif;
        font-weight: 200;
        color: #444444;
        line-height: 20px;
    }


    #oink-checkout-button {
        float: left;
    }

    .overlay_magento {
        background-color: #000;
        filter:alpha(opacity=60);
        -moz-opacity: 0.6;
        opacity: 0.6;
    }

    div#info-panel {
        color: #999999;
        display:inline-block;
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        width:180px;
        height:253px;
        padding: 10px 10px 0px 15px;
        vertical-align:top;
        background-color: #F3F3F3;
        border-radius: 4px;
    }

    .dim
    {
        background-color: white;
        filter:alpha(opacity=50); /* IE */
        opacity: 0.5; /* Safari, Opera */
        -moz-opacity:0.50; /* FireFox */
        z-index: 20;
    }

    #oink-login #vp-close {
        background: url('<?php echo $skinUrl; ?>x.png') no-repeat;
        cursor: pointer;
        height: 17px;
        position: absolute;
        right: 30px;
        top: 30px;
        width: 17px;
    }

    #login-form-button {
        border: 1px solid #EE7A27;
        background-color: #F57D28;
        background: -moz-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f68b3e), color-stop(100%, #ee7a27));
        background: -webkit-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -o-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -ms-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: linear-gradient(to bottom, #f68b3e 0%, #ee7a27 100%);
    }
    #sign-up-button {
        width: 130px;
        height: 26px;
        line-height:26px;
        border: 1px solid #03A2A7;
        background-color: #0AA5A8;
        margin-left:415px;
        margin-top:-47px;
        background: -moz-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #39c4cb), color-stop(100%, #03a2a7));
        background: -webkit-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -o-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -ms-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: linear-gradient(to bottom, #39c4cb 0%, #03a2a7 100%);
    }
    .oink-button {
        color: #ffffff;
        cursor: pointer;
        text-decoration: none;
        height: 28px;
        font-size: 14px;
        min-width: 88px;
        border-radius: 4px;
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        display:inline-block;
        vertical-align: middle;
    }

    .oink-note {
        color: #666666;
        font-size: 11px;
        text-decoration: none;
        font-family: Helvetica,'Open Sans Condensed',sans-serif;
        font-weight: 200;
    }

    #oink-login {
        float: left;
        display: inline-block;
        width: 350px;
        position: relative;
        background-color: white;
        box-shadow: 3px 0px 5px -2px rgba(0, 0, 0, 0.25);
        padding: 0px 20px 0px 20px;
        height:300px;
        border-top-left-radius:4px;
        border-bottom-left-radius:4px;
    }
    #oink-login-userid, #oink-login-password
    {
        border: 1px solid #c0c0bf;
        border-radius: 4px;
        color: #666;
        font-size: 10pt;
        padding: 5px;
        width: 345px;
        text-decoration: none;
        font-family: Helvetica,'Open Sans Condensed',sans-serif;
    }

    div#oink-modal {
        background-color: #F3F3F3;
        box-shadow: 0 10px 10px rgba(0,0,0,0.3);
        border-radius: 4px;
        height: 300px;
    }
    .oink-block{
        border-radius: 4px;
        background-color: #F3F3F3;
    }
</style>

<?php $skinUrl = $this->getSkinUrl('images/oink/checkout/'); ?>
<?php $baseJsUrl = Mage::getBaseUrl('js'); ?>

<link rel="stylesheet" type="text/css" href="<?php echo $baseJsUrl ?>prototype/windows/themes/default.css"/>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:bold&v1' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="<?php echo $baseJsUrl ?>prototype/window.js"></script>

<div id="oink-modal" align="center" style="display:none;">
    <div align="left" class="oink-block">
        <!-- x //-->
        <div style="float:right;padding:10px;"><a style="text-decoration:none;cursor:pointer;" onClick="return closePopup()"><img src="<?php echo $skinUrl; ?>x.png" /></a></div>

        <!-- left col -->
        <div id="oink-login" align="center">
            <form id="oink-checkout">
                <img src="//cdn.virtualpiggy.com/public/images/checkout-logo-192x75.png" height="80" style="padding-top:20px; padding-bottom:20px;"/>
                <div align="center" style="padding-top:10px;">
                    <input class="textBox required-entry" onkeypress="bindOinkLoginPost(event)" id="oink-login-userid" name="UserName" tabindex="2" type="text" placeholder="Username" />
                </div>
                <div align="center" style="padding-top:5px;">
                    <input autocomplete="off" onkeypress="bindOinkLoginPost(event)" class="textBox required-entry" id="oink-login-password" name="Password" tabindex="3" type="password" placeholder="Password" />
                    <div class="opensans" style="font-size:10pt;color:#ff0000;" id="oink-errors-container">&nbsp;</div>
                    <div><a href="//users.virtualpiggy.com/login/resetpassword" target="_blank" class="oink-note" style="margin-top: 14px">Forgot Password?</a></div>
                    <button onclick="return oinkLoginForm.submit();" id="login-form-button" class="oink-button" type="button">Login</button>
                </div>
            </form>
            <a href="//users.virtualpiggy.com/registration" target="_blank" id="sign-up-button" class="oink-button">Sign Up</a>
        </div>
    </div>
    <div align="right" style="margin:0px; background-color:#F3F3F3; border-radius:4px;">
        <div id="info-panel" align="center">
            <div>
                <span class="oink-h2">What is Oink?</span>
            </div>
            <div style="padding-top:15px;">
                <span style="font-size:10pt;font-family:"helvetica neue regular";color:#444;line-height:10px;">Oink is the safe way for kids and teens to save, shop and give online.</span>
            </div>
            <div style="padding-top:63px;">
                <a href="//www.oink.com/" target="_blank" class="oink-note">Learn More</a>
            </div>
        </div>
        <div id="oink-loading" style="vertical-align:top;display:none;border-radius:4px;margin:0px;background-color:white">
            <div align="center">
                <img src="https://cdn.virtualpiggy.com/public/images/checkout-logo-192x75.png" height="80" style="padding-bottom:20px;"/>
                <div align="center" class="oink-h2" style="width:220px;padding-top:15px;"><span><?php echo Mage::helper('adminhtml')->__('Please wait while you are logged in...') ?></span></div>
                <div align="center" style="padding-top:20px; padding-bottom:20px;"><img src="<?php echo $this->getSkinUrl('images/oink/login/loader.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/></div>
            </div>
        </div>
    </div>
</div>


<input type="hidden" id="oink-checkout-url" value="<?php echo $this->getCheckoutUrl() ?>"/>
<script type="text/javascript">
    //<![CDATA[
    if($('p_method_oink'))
        $('p_method_oink').checked=false;

    if ("payment" in window)
    {
        var oldSwitchMethod=payment.switchMethod;
        payment.switchMethod=function(method){
            if(method=="oink"){
                oinkLoginForm.toggleTooltip()
            }else{
                oldSwitchMethod.apply(this,[method])
            }
        }
    }

    function closePopup(){
        if($('p_method_oink'))$('p_method_oink').checked=false;
        Dialog.cancelCallback();
        return false;
    }

    var oinkLoginForm = new VarienForm('oink-modal', true);
    function bindOinkLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            oinkLoginForm.submit();
        }
    }
    oinkLoginForm.toggleTooltip=function(){
        if($$(".dialog").length){
            if($('p_method_oink'))$('p_method_oink').checked=false;
            return false;
        }
        if($('p_method_oink')){
            $('p_method_oink').checked = 1;
        }
        Dialog.info($('oink-modal').innerHTML, {
            className:"magento",
            width:600,
            height:300,
            top: 175
        });
        return false;
    }

    oinkLoginForm.submit=function(){
        var user=$('oink-login-userid').value;
        var password=$('oink-login-password').value;

        if(this.validator && this.validator.validate()){
            new Ajax.Request("<?php echo $this->getLoginPostUrl() ?>",{
                method:"post",
                parameters:{
                    "user" : user,
                    "password" : password
                },

                onCreate:function() {
                    $('oink-login').setStyle({ display: 'none'});
                    $('info-panel').setStyle({display: 'none'});
                    $('login-form-button').innerHTML = '<img src="<?php echo $skinUrl; ?>login.png" />';
                    $('oink-loading').setStyle({ display: 'inline-block', width: '600px'});
                },

                onComplete:function(){},

                onSuccess:function(transport) {
                    var json=eval('(' + transport.responseText + ')');

                    if(json.response) {
                        setLocation($("oink-checkout-url").value);
                        $('oink-errors-container').innerHTML = '';
                    } else
                    {
                        $('oink-errors-container').innerHTML = json.errorMessage;
                        $('oink-loading').setStyle({ display: 'none'});
                        $('oink-login').setStyle({ display: 'inline-block'});
                        $('info-panel').setStyle({display: 'inline-block'}).removeClassName('dim');
                        $('login-form-button').innerHTML = '<button onclick="return oinkLoginForm.submit();" id="login-form-button" class="oink-button" type="button">Login</button>';
                    }
                }
            });
        }

        return false;
    }
    //]]>
</script>