<style>
    #oink-login-container{
        position:relative;
    }
    input[type=text], input[type=password]
    {
        height:25px;
        width:250px;
        font-size:11pt;
        color: #444;
        padding-left: 10px;
        text-decoration: none;
        font-family: "helvetica neue regular";
    }

    #oink-cart-button {
        display: inline-block;
        margin-top: <?php echo Mage::getStoreConfig("oink/checkoutbutton/oink_cart_checkout_margin_top").'px;'; ?>
    }

    .opensans
    {
        font-family: "open sans condensed", sans-serif;
        font-style:condensed;
        font-size:16pt;
        font-weight:bold;
        color:#1E6FCA;
        line-height: 15px;
    }


    #oink-checkout-button {
        float: left;
    }

    .overlay_magento {
        background-color: #000;
        filter:alpha(opacity=60);
        -moz-opacity: 0.6;
        opacity: 0.6;
    }

    .dim
    {
        background-color: white;
        filter:alpha(opacity=50); /* IE */
        opacity: 0.5; /* Safari, Opera */
        -moz-opacity:0.50; /* FireFox */
        z-index: 20;
    }


</style>

<?php $skinUrl = $this->getSkinUrl('images/oink/checkout/'); ?>
<?php $baseJsUrl = Mage::getBaseUrl('js'); ?>

<link rel="stylesheet" type="text/css" href="<?php echo $baseJsUrl ?>prototype/windows/themes/default.css"/>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:bold&v1' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="<?php echo $baseJsUrl ?>prototype/window.js"></script>
<div id="oink-login" align="center" style="display:none;">
    <div align="left" style="width:600px;height:300px;border:1px solid #444;background-color:#fff;">

        <!-- x //-->
        <div style="float:right;padding:10px;"><a style="text-decoration:none;cursor:pointer;" onClick="return closePopup()"><img src="<?php echo $skinUrl; ?>x.png" /></a></div>
        <div style="padding:30px;">

            <!-- left col -->
            <div id="loading" style="vertical-align:top;display:none;width:310px;height:200px;">
                <div align="center">
                    <img src="https://cdn.oink.com/public/images/checkout-logo-192x75.png" />
                    <div align="center" class="opensans" style="width:220px;padding-top:15px;"><span style="font-weight:bold;color:#999;"><?php echo Mage::helper('adminhtml')->__('Please wait while you are logged in...') ?></span></div>
                    <div align="center" style="padding-top:20px;"><img src="<?php echo $this->getSkinUrl('images/oink/login/loader.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/></div>
                </div>
            </div>

            <div id="login" style="vertical-align:top;display:inline-block;width:310px;height:200px;">
                <div align="center">
                    <form id="oink-login">
                        <img src="https://cdn.oink.com/public/images/checkout-logo-192x75.png" height="70"/>
                        <div class="opensans" style="font-size:16pt;font-weight:bold;color:#999;padding-top:15px;">Log In to Checkout</div>
                        <div align="center" style="padding-top:10px;">
                            <input class="textBox required-entry" onkeypress="bindOinkLoginPost(event)" id="oink-login-userid" name="UserName" tabindex="2" type="text" placeholder="Username" />
                        </div>
                        <div align="center" style="padding-top:5px;">
                            <input autocomplete="off" onkeypress="bindOinkLoginPost(event)" class="textBox required-entry" id="oink-login-password" name="Password" tabindex="3" type="password" placeholder="Password" />
                            <div class="opensans" style="font-size:10pt;color:#ff0000;" id="oink-errors-container">&nbsp;</div>
                            <div><a href="https://users.oink.com/login/forgotpassword" target="_blank" style="font-size:10pt;color:#999;font-family:"helvetica neue regular";">Forgot Password?</a></div>
                        </div>
                    </form>
                </div>
            </div>

            <!-- separator -->
            <div style="display:inline-block;height:210px;width:0px;border:1px solid #999;"></div>

            <!-- right col -->
            <div id="signup" style="vertical-align:top;display:inline-block;width:180px;height:200px;padding-left:15px;">
                <div align="center" style="padding-top:30px;">
                    <div style=""><span class="opensans">Don't have an Oink account?</span></div>
                    <div style="padding-top:15px;"><span style="font-size:10pt;font-family:"helvetica neue regular";color:#444;line-height:10px;">Oink is the safe way for kids and teens to save, shop and give online.</span></div>
                    <div style="padding-top:35px;"><a href="http://www.oink.com/how-it-works" target="_blank" style="font-size:10pt;color:#999;font-family:"helvetica neue regular";">Learn More</a></div>
                </div>
            </div>

            <!-- buttons -->
            <div id="buttons">
                <div id="button-login" align="center" style="display:inline-block;width:310px;"><a onclick="return oinkLoginForm.submit();" href="#"><img src="<?php echo $skinUrl; ?>login.png" /></a></div>
                <div id="button-signup" align="center" style="display:inline-block;width:220px;"><a href="https://users.oink.com/registration" target="_blank" style="font-size:10pt;font-family:helvetica, neue, regular;color:#999;"><img src="<?php echo $skinUrl; ?>signup.png" /></a></div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="oink-checkout-url" value="<?php echo $this->getCheckoutUrl() ?>"/>
<script type="text/javascript">
    //<![CDATA[ 
    if ("payment" in window)
    {
        var oldSwitchMethod=payment.switchMethod;
        payment.switchMethod=function(method){
            if(method=="oink"){
                oinkLoginForm.toggleTooltip()
            }else{
                oldSwitchMethod.apply(this,[method])
            }
        }
    }
    // if($('p_method_oink')){  
    //    $('p_method_oink').onclick=function(){  
    //      oinkLoginForm.submit();  
    //     }  
    // } 
    function closePopup(){
        if($('p_method_oink'))$('p_method_oink').checked=false;
        Dialog.cancelCallback();
        return false;
    }
    var oinkLoginForm = new VarienForm('oink-login', true);
    function bindOinkLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            oinkLoginForm.submit();
        }
    }
    oinkLoginForm.toggleTooltip=function(){
        if($$(".dialog").length){
            return false;
        }
        if($('p_method_oink')){
            $('p_method_oink').checked=1;
        }
        Dialog.info($('oink-login').innerHTML, {
            className:"magento",
            width:600,
            height:300,
            top: 175,
        });
        return false;
    }

    oinkLoginForm.submit=function(){
        var user=$('oink-login-userid').value;
        var password=$('oink-login-password').value;

        if(this.validator && this.validator.validate()){
            new Ajax.Request("<?php echo $this->getLoginPostUrl() ?>",{
                method:"post",
                parameters:{
                    "user" : user,
                    "password" : password
                },

                onCreate:function() {
                    $('loading').setStyle({ display: 'inline-block'});
                    $('login').setStyle({ display: 'none'});
                    $('signup').addClassName('dim');
                    $('button-login').innerHTML = '<img src="<?php echo $skinUrl; ?>login.png" />';
                    $('buttons').addClassName('dim');
                },

                onComplete:function(){},

                onSuccess:function(transport) {
                    var json=eval('(' + transport.responseText + ')');

                    if(json.response) {
                        setLocation($("oink-checkout-url").value);
                        $('oink-errors-container').innerHTML = '';
                    } else
                    {
                        $('oink-errors-container').innerHTML = json.errorMessage;
                        $('loading').setStyle({ display: 'none'});
                        $('login').setStyle({ display: 'inline-block'});
                        $('signup').removeClassName('dim');
                        $('button-login').innerHTML = '<a onclick="return oinkLoginForm.submit();" href="#"><img src="<?php echo $skinUrl; ?>login.png" /></a>';
                        $('buttons').removeClassName('dim');
                    }
                }
            });
        }

        return false;
    }

    //]]>
</script>