<style>
    #oink-checkout {
        border-radius: 4px;
        background:white;
    }


    #oink-cart-button {
        display: inline-block;
        margin-top: <?php echo Mage::getStoreConfig("oink/checkoutbutton/oink_cart_checkout_margin_top").'px;'; ?>
    }

    .oink-h2
    {
        padding-bottom: 5px;
        font-size: 19px;
        display: block;
        text-align: center;
        font-family: Helvetica,'Open Sans Condensed',sans-serif;
        font-weight: 200;
        color: #444444;
        line-height: 20px;
    }


    #oink-checkout-button {
        float: left;
    }

    .overlay_magento {
        background-color: #000;
        filter:alpha(opacity=60);
        -moz-opacity: 0.6;
        opacity: 0.6;
    }

    div#info-panel {
        color: #999999;
        display:inline-block;
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        width:180px;
        height:253px;
        padding: 50px 10px 0px 15px;
        vertical-align:top;
        background-color: #F3F3F3;
        border-radius: 4px;
    }

    .dim
    {
        filter:alpha(opacity=50); /* IE */
        opacity: 0.5; /* Safari, Opera */
        -moz-opacity:0.50; /* FireFox */
    }

    #oink-login #vp-close {
        background: url('<?php echo $skinUrl; ?>x.png') no-repeat;
        cursor: pointer;
        height: 17px;
        position: absolute;
        right: 30px;
        top: 30px;
        width: 17px;
    }

    #login-form-button {
        border: 1px solid #EE7A27;
        background-color: #F57D28;
        background: -moz-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f68b3e), color-stop(100%, #ee7a27));
        background: -webkit-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -o-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -ms-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: linear-gradient(to bottom, #f68b3e 0%, #ee7a27 100%);
    }
    #sign-up-button {
        width: 130px;
        height: 26px;
        line-height:26px;
        border: 1px solid #03A2A7;
        background-color: #0AA5A8;
        margin-left:415px;
        margin-top:-47px;
        background: -moz-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #39c4cb), color-stop(100%, #03a2a7));
        background: -webkit-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -o-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -ms-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: linear-gradient(to bottom, #39c4cb 0%, #03a2a7 100%);
    }
    .oink-button {
        color: #ffffff;
        cursor: pointer;
        text-decoration: none;
        height: 28px;
        font-size: 14px;
        min-width: 88px;
        border-radius: 4px;
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        display:inline-block;
        vertical-align: middle;
    }

    .oink-note {
        color: #666666;
        font-size: 11px;
        text-decoration: none;
        font-family: Helvetica,'Open Sans Condensed',sans-serif;
        font-weight: 200;
    }

    #oink-login {
        float: left;
        display: inline-block;
        width: 350px;
        position: relative;
        background-color: white;
        box-shadow: 3px 0px 5px -2px rgba(0, 0, 0, 0.25);
        padding: 0px 20px 0px 20px;
        height:303px;
        border-top-left-radius:4px;
        border-bottom-left-radius:4px;
    }
    #oink-login-userid, #oink-login-password
    {
        border: 1px solid #c0c0bf;
        border-radius: 4px;
        color: #666;
        font-size: 10pt;
        padding: 5px;
        width: 345px;
        text-decoration: none;
        font-family: Helvetica,'Open Sans Condensed',sans-serif;
    }

    div#oink-modal {
        background-color: #F3F3F3;
        box-shadow: 0 10px 10px rgba(0,0,0,0.3);
        border-radius: 4px;
        height: 300px;
    }
    .oink-block{
        border-radius: 4px;
        background-color: #F3F3F3;
    }
    #oink-close {
        float:right;
        padding-top:10px;
        position: relative;
        left:10px;
    }
    .spinner {
        text-align: center;
        display:none;
        border-radius:4px;
        margin:0;
        width: 350px;
    }

    .spinner img {
        width: 54px;
        height: 54px;
        margin-top: 55px;
        margin-bottom: 10px;

        -webkit-transition-property: -webkit-transform;
        -webkit-transition-duration: 1s;
        -moz-transition-property: -moz-transform;
        -moz-transition-duration: 1s;
        -webkit-animation-name: spinner-rotate;
        -webkit-animation-duration: 1s;
        -webkit-animation-iteration-count: infinite;
        -webkit-animation-timing-function: linear;
        -moz-animation-name: spinner-rotate;
        -moz-animation-duration: 1s;
        -moz-animation-iteration-count: infinite;
        -moz-animation-timing-function: linear;
    }

    @-webkit-keyframes spinner-rotate {
        from {-webkit-transform: rotate(0deg);}
        to {-webkit-transform: rotate(360deg);}
    }

    @-moz-keyframes spinner-rotate {
        from {-moz-transform: rotate(0deg);}
        to {-moz-transform: rotate(360deg);}
    }

    .spinner h3 {
        margin-bottom: 5px;

        font-size: 1.3em;
    }

    .spinner p {
        margin: 0;
    }

</style>

<?php $skinUrl = $this->getSkinUrl('images/oink/checkout/'); ?>
<?php $baseJsUrl = Mage::getBaseUrl('js'); ?>

<link rel="stylesheet" type="text/css" href="<?php echo $baseJsUrl ?>prototype/windows/themes/default.css"/>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:bold&v1' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="<?php echo $baseJsUrl ?>prototype/window.js"></script>

<div id="oink-modal" align="center" style="display:none;">
    <div align="left" class="oink-block">
        <!-- left col -->
        <div id="oink-login" align="center">
            <div id="oink-close"><a style="text-decoration:none;cursor:pointer;" onClick="return closePopup()"><img src="<?php echo $skinUrl; ?>x.png" /></a></div>
            <img src="//cdn.virtualpiggy.com/public/images/checkout-logo-192x75.png" height="80" style="padding-top:20px; padding-bottom:20px;"/>
            <form id="oink-checkout">
                <div align="center" style="padding-top:10px;">
                    <input class="textBox required-entry" onkeypress="bindOinkLoginPost(event)" id="oink-login-userid" name="UserName" tabindex="2" type="text" placeholder="Username" />
                </div>
                <div align="center" style="padding-top:5px;">
                    <input autocomplete="off" onkeypress="bindOinkLoginPost(event)" class="textBox required-entry" id="oink-login-password" name="Password" tabindex="3" type="password" placeholder="Password" />
                    <div class="opensans" style="font-size:10pt;color:#ff0000;" id="oink-errors-container">&nbsp;</div>
                    <div><a href="//users.virtualpiggy.com/login/resetpassword" target="_blank" class="oink-note" style="margin-top: 14px">Forgot Password?</a></div>
                    <button onclick="return oinkLoginForm.submit();" id="login-form-button" class="oink-button" type="button">Login</button>
                </div>
            </form>

            <a href="//users.virtualpiggy.com/registration" target="_blank" id="sign-up-button" class="oink-button">Sign Up</a>
            <div id="oink-loading" class="spinner page">
                <img src="<?php echo $skinUrl; ?>spinner.png" alt="" />
            </div>
        </div>
    </div>
    <div align="right" style="margin:0px; background-color:#F3F3F3; border-radius:4px;">
        <div id="info-panel" align="center">
            <div>
                <span class="oink-h2">What is Oink?</span>
            </div>
            <div style="padding-top:15px;">
                <span style="font-size:10pt;color:#444;">Oink is the safe way for kids and teens to save, shop and give online.</span>
            </div>
            <div style="padding-top:60px">
                <a href="//www.oink.com/" target="_blank" class="oink-note">Learn More</a>
            </div>
        </div>
    </div>
</div>


<input type="hidden" id="oink-checkout-url" value="<?php echo $this->getCheckoutUrl() ?>"/>
<script type="text/javascript">
    //<![CDATA[
    function showSpinner() {
        $('oink-checkout').setStyle({ display: 'none'});
        $('oink-login').setStyle({backgroundColor: '#BBBBBB'}).addClassName('dim');
        $('oink-loading').setStyle({ display: 'block'});
        $('sign-up-button').setStyle({ display: 'none'});
        return false;
    }

    function hideSpinner() {
        $('oink-loading').setStyle({ display: 'none'});
        $('oink-checkout').setStyle({ display: 'block'});
        $('oink-login').setStyle({backgroundColor: 'white'}).removeClassName('dim');
        $('sign-up-button').setStyle({ display: 'inline-block'});
    }

    function closePopup(){
        if($('p_method_oink'))$('p_method_oink').checked=false;
        Dialog.cancelCallback();
        return false;
    }

    function bindOinkLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            oinkLoginForm.submit();
        }
    }

    if ("payment" in window)
    {
        var oldSwitchMethod=payment.switchMethod;
        payment.switchMethod=function(method){
            if(method=="oink"){
                oinkLoginForm.toggleTooltip()
            }else{
                oldSwitchMethod.apply(this,[method])
            }
        }
    }

    var oinkLoginForm = new VarienForm('oink-modal', true);

    oinkLoginForm.toggleTooltip=function(){
        if($$(".dialog").length){
            return false;
        }
        if($('p_method_oink')){
            $('p_method_oink').checked=1;
        }
        if (screen.width < 700 || screen.height < 400) {
            $('info-panel').setStyle({ display: 'none'});
            $('sign-up-button').setStyle({ display: 'none'});
            $('oink-login').setStyle({ borderRadius: '4px', boxShadow: 'none'});
            Dialog.info($('oink-modal').innerHTML, {
                className:"magento",
                width: 370,
                height:300,
                top: 0,
                left: ((screen.width - (370))/2),
                recenterAuto:true
            });
        } else {
            Dialog.info($('oink-modal').innerHTML, {
                className:"magento",
                width:600,
                height:300,
                top: ((window.innerHeight - 300)/2),
                left: ((window.innerWidth - 600)/2),
                recenterAuto:true
            });
            $('oink-close').setStyle({ left: '220px'});
        }
        return false;
    }

    oinkLoginForm.submit=function(){
        var user=$('oink-login-userid').value;
        var password=$('oink-login-password').value;

        if(this.validator && this.validator.validate()){
            new Ajax.Request("<?php echo $this->getLoginPostUrl() ?>",{
                method:"post",
                parameters:{
                    "user" : user,
                    "password" : password
                },

                onCreate:function() {
                    $('info-panel').addClassName('dim');
                    showSpinner();
                },

                onComplete:function(){},

                onSuccess:function(transport) {
                    var json=eval('(' + transport.responseText + ')');

                    if(json.response) {
                        setLocation($("oink-checkout-url").value);
                        $('oink-errors-container').innerHTML = '';
                    } else
                    {
                        hideSpinner();
                        $('oink-errors-container').innerHTML = json.errorMessage;
                        $('oink-login').setStyle({ display: 'inline-block'});

                        if (screen.width >= 700 || screen.height >= 400) {
                            $('info-panel').setStyle({display: 'inline-block'}).removeClassName('dim');
                        }
                        $('login-form-button').innerHTML = '<button onclick="return oinkLoginForm.submit();" id="login-form-button" class="oink-button" type="button">Login</button>';
                    }
                }
            });
        }

        return false;
    }
    //]]>
</script>